# Generated by Django 5.2.9 on 2026-03-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_entrydata_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydata',
            name='algo_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
